### ISSUE TITLE
Cannot migrate using Bolt protocol

### ISSUE THREAD

**Issue by floriandejonckheere** [floriandejonckheere/headbanger#1]
The Neo4j database cannot be migrated using the Bolt protocol. Migrations over HTTP run fine.

```
rails aborted!
NoMethodError: undefined method `signature' for 46:Integer
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/neo4j-core-7.0.4/lib/neo4j/core/cypher_session/adaptors/bolt.rb:201:in `block in flush_messages'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/neo4j-core-7.0.4/lib/neo4j/core/cypher_session/adaptors/bolt.rb:200:in `map'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/neo4j-core-7.0.4/lib/neo4j/core/cypher_session/adaptors/bolt.rb:200:in `flush_messages'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/neo4j-core-7.0.4/lib/neo4j/core/cypher_session/adaptors/bolt.rb:35:in `connect'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/neo4j-core-7.0.4/lib/neo4j/core/cypher_session.rb:11:in `initialize'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/neo4j-8.0.6/lib/neo4j/session_manager.rb:17:in `new'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/neo4j-8.0.6/lib/neo4j/session_manager.rb:17:in `open_neo4j_session'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/neo4j-8.0.6/lib/neo4j/railtie.rb:65:in `setup!'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/neo4j-8.0.6/lib/neo4j/railtie.rb:51:in `block (2 levels) in <class:Railtie>'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/neo4j-8.0.6/lib/neo4j/active_base.rb:18:in `establish_session'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/neo4j-8.0.6/lib/neo4j/active_base.rb:8:in `current_session'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/neo4j-8.0.6/lib/neo4j/shared.rb:17:in `neo4j_session'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/neo4j-8.0.6/lib/neo4j/active_node/labels.rb:143:in `mapped_label'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/neo4j-8.0.6/lib/neo4j/migrations/runner.rb:16:in `initialize'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/neo4j-8.0.6/lib/neo4j/tasks/migration.rake:52:in `new'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/neo4j-8.0.6/lib/neo4j/tasks/migration.rake:52:in `block (3 levels) in <top (required)>'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/neo4j-8.0.6/lib/neo4j/tasks/migration.rake:46:in `block (2 levels) in <top (required)>'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/railties-5.0.1/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/florian/.rvm/gems/ruby-2.4.0@headbanger/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
```

**Comment by floriandejonckheere** [comment]
Solution: use the TCP port for Bolt, not HTTP.
